# Generated by Django 3.1.2 on 2020-10-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryurl',
            name='final_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
