# Generated by Django 3.1.2 on 2020-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainurl',
            name='file',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
